spring.datasource.url=jdbc:mysql://localhost:3306/product_db?useSSL=false&serverTimezone=Asia/Jakarta&characterEncoding=UTF-8&useUnicode=true&charset=utf8mb4&allowPublicKeyRetrieval=true
spring.datasource.username=product_admin
spring.datasource.password=Semogasukses99
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-test-query=SELECT 1


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true



spring.jpa.properties.hibernate.connection.characterEncoding=utf-8
spring.jpa.properties.hibernate.conneection.CharSet=utf-8
spring.jpa.properties.hibernate.connection.useUnicode=true
spring.jpa.properties.hibernate.connection.characterSetResults=utf-8


server.port=8080
server.servlet.context-path=/api


logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


spring.jackson.encoding=UTF-8
spring.jackson.default-property-inclusion=non_null
